# Generated by Django 4.2.7 on 2023-11-20 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('isSingleton', models.BooleanField(default=False, verbose_name='Единственный экземпляр')),
            ],
            options={
                'verbose_name': 'Тип документа',
                'verbose_name_plural': 'Типы документов',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('designation', models.CharField(max_length=100, verbose_name='Обозначение')),
                ('room_name', models.CharField(max_length=100, verbose_name='Название комнаты')),
                ('product_designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_products', to=settings.AUTH_USER_MODEL, verbose_name='Дизайнер продукта')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('designation', models.CharField(max_length=100, verbose_name='Обозначение')),
                ('project_designer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Дизайнер проекта')),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='WorkDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Содержимое')),
                ('isArchived', models.BooleanField(default=False, verbose_name='Архивирован')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs.documenttype', verbose_name='Тип документа')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.product', verbose_name='Продукт')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Рабочий документ',
                'verbose_name_plural': 'Рабочие документы',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='docs.project', verbose_name='Проект'),
        ),
    ]
