# Generated by Django 4.2.7 on 2023-11-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdocument',
            name='content',
            field=models.FileField(upload_to='documents/', verbose_name='Файл'),
        ),
    ]
