# Generated by Django 4.2.7 on 2023-11-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Изделие', 'verbose_name_plural': 'Изделия'},
        ),
    ]
