# Generated by Django 4.2.7 on 2023-11-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0009_alter_product_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='product',
            name='designation',
            field=models.CharField(max_length=30, verbose_name='Обозначение'),
        ),
        migrations.AlterField(
            model_name='workdocument',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='docs.product', verbose_name='Изделие'),
        ),
    ]
