# Generated by Django 4.2.7 on 2023-11-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_product_description_alter_product_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Информация'),
        ),
    ]
