# Generated by Django 4.2.7 on 2023-11-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0011_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='sub_folder',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к папке для сохранения'),
        ),
        migrations.AddField(
            model_name='project',
            name='path_to_project_folder',
            field=models.CharField(blank=True, max_length=255, verbose_name='Путь к папке для сохранения'),
        ),
    ]
