# Generated by Django 4.2.7 on 2023-11-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0012_documenttype_sub_folder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workdocument',
            name='content',
            field=models.FileField(max_length=300, upload_to='documents/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='workdocument',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
