# Generated by Django 5.0 on 2023-12-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0013_alter_workdocument_content_alter_workdocument_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='workdocument',
            name='backup_saved',
            field=models.BooleanField(default=False, verbose_name='Backup сохранен'),
        ),
        migrations.AddField(
            model_name='workdocument',
            name='path_to_backup',
            field=models.CharField(blank=True, max_length=300, verbose_name='Путь к backup файлу'),
        ),
    ]
