# Generated by Django 4.2.7 on 2023-11-28 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_folder',
            field=models.FilePathField(blank=True, default=None, null=True, path='c:\\temp'),
        ),
    ]
