# Generated by Django 4.2.7 on 2023-11-18 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0002_alter_section_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='footer',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
