# Generated by Django 4.2.7 on 2023-11-18 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regulation', '0003_alter_section_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'файл', 'verbose_name_plural': 'файлы'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'изображение', 'verbose_name_plural': 'изображения'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'раздел', 'verbose_name_plural': 'разделы'},
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=200, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='файл'),
        ),
        migrations.AlterField(
            model_name='file',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='regulation.section', verbose_name='раздел'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='подпись'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='regulation.section', verbose_name='раздел'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content',
            field=models.TextField(verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='section',
            name='footer',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='нижний колонтитул'),
        ),
        migrations.AlterField(
            model_name='section',
            name='header',
            field=models.CharField(max_length=200, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=100, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regulation.section', verbose_name='родительский раздел'),
        ),
    ]
